language: java
jdk: oraclejdk8
services:
  - mysql
before_script:
  - mysql -utravis -e "create database demo"
addons:
  ssh_known_hosts: 52.78.120.44
before_deploy:
  - openssl aes-256-cbc -K $encrypted_dfdeba1a9a1d_key -iv $encrypted_dfdeba1a9a1d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - secure: C7MGKvqa5MGi4Lvi+fTBfxawyLitj1S/8U1sMz2bxTfmW5rBAtzJrFmtbiGj5zqn0vak0aNAJEG3okE+WWl4JEbuZ5VA6ftUfe1/saBnKj8d2Fs5hdKsLmEI78hzv9zjZmvU2uTdbpTTY9k6Co+KyxUBTKoXhroIYpSRT3ThddAendrL0Lc800NkV4WFz5f9bsSYbxfulGEwNMJuCa6uFl/g7RRoaUbVHfB17vaPp8YNd3lfDk5OQ6sIlHi3KeB4N6CTB04EZOAoZIk/Ac4Kb8bUVWj5y12VPplnnME6VVHm4cqgXGwpFWK9rVVaAAnrOA0jdKcHLEAf2NOgwOy4X81wmBThC/9GMVuKyLTbrrb0fh4GaiBeISDAt0pR4qXWdFmoXP56OXFkRgkQMNFiNW5QKQj8EMgXIwUDviUhVZ/2YiUaZHvCD6RL+TgCrvPNLg48KbcBck2/MZ2Fhn26Zktcsb64n3SGnaWVSR2WqHV/SE2GTfPoSBO0080GdZPt02OB/F3MchAOQ4m7loSlv00ViTxlyIjJaBQOaUvtzMFmTdQIngzbBLMs33zDSDRLm4JKOjCIriC9ouCutG5sp9M0zBpKZxg9u1nB0gvwjO+NgHc+bUlwV+e/iAP4aSsi3Y1zquddyrsdLwM8UI1YDz4msMsPo4GBQ/2gUKWGhJU=
    - secure: Nvb7GGHmhT324vBhktot//ZMk15QNj5ZsRb+dj7TjEEgB6I+aYqduRV4KgCtCS7yQiJz5h38agOmU50TETb6fV5mG7/UZyu5/t71kZiOtZsqxYAtJV2Aspp2c6kiT7R50v8gMtF/Jd5jNoXmsLzPh+njc/fbq2kFS17m3/7Bx3OHJj9z5I1FDLgfeMFKENYYSJzZW+LUwhY9Z0ozY2X3dif70GwnCLDB3MJ/yWAMUov7bJSaMPHfuD9nLyNyy3c3BxXQjDDre1UnKe/g70MIQf8enFeggJwOElXZ+Kf3kqlX60sakZ/9QxWiGiwy2sJkpzQeUZHGgcmHHi/RrG+D4wbb/jyUgMtK8XualhshR4HzDI8PzQhUHXG8VNgwl/lGJZ12vqETrUBuZdncnxf2RdDKbU3xnH1kB5zhx3v/s6vCcyM1skUIOL1WQVpG5vTy/VFZC2niYqH+CVCByjSCbM4S5C4il827BQ0+CmfejiORXZVwNmq2P3xefKRbyXPKIG6mrfTaY2Rx0dHxprcvR2g2W4OboNdtEjj9lK6Hmay74Jxw+8p7LbGxwFecutJAAnXehzS3Ss26o8f4ncIY/NJp9qbKbWxM2/io4Iz6aJOtV58K5uMcoZzjMtKnDXbjVj44vYAHh3Hhqko5jnO3JQvK4guD+6MCoegtB5b1DQ0=
    - secure: a4HkF2XE7Vpfh+1vys48g9IqKGAThEa3xzLeADQdZC61NfVQNKF0xuQzIKxXxoAlnbsk5LvLyvEzjTE81WX4IjolYCM+UPPqyXC37ige3Mv8bFuYvaZ/pzum5At9ZXa+Nl3Y1BvL1TEZggToi/hnl5bwHg+OWGPfha3OTXeemKEKDSZNA63YmBehKrgWU2ztCmOlpgcX/1xZTYh/3aCEo3rjuCFsl3F0TzUmIw5R7EqdJz823Jbo4qJwmlTsP5Ix7U/rL2uFOXpaoAOm/g4nrv2FK55ByHEKesC/re1F44wSw33Z3K2PFwnHJoDkxA6/UNqu+uYCQqOBi1BsPBeyh2TiglCbU1jiBJ9qXrBTm35Im0Lt/0hMn5Y4iNcCMEmjpx4shd5s01XQgxCZbvOXO505s6TVP16IN/oJjc+s8R4BJ+EAK5t3sIm4FaazkzOFhT/za8esFg4ya6E6VT4cjKgbfUfTFFSLy+y5pbxP/XEyottE0ErlfW/+hiGijtzt1IbM6HUoAlOmRXdUCV4ixskcGSad3QhvKlwVRYTnTtzK9LQQ2+UBOoCoWoQlbbDqXFPOJMQaCe5Wp9vxYfe/zq1IE+WOGhLFNlIjlGQgy6OqJ5C7a52wNanR4z9aEhP34UAWj3/eNc4htI7YEo+I5wt/hhOS/n+DzGDNf5Rv1R4=