language: java
jdk: oraclejdk8
services:
- mysql
before_script:
- mysql -utravis -e "create database demo"
addons:
  ssh_known_hosts: 52.78.120.44
before_deploy:
- openssl aes-256-cbc -K $encrypted_dfdeba1a9a1d_key -iv $encrypted_dfdeba1a9a1d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp /home/travis/build/voidreamy/demo/target/demo-0.0.1-SNAPSHOT.war ec2-user@52.78.120.44:~
  on:
    branch: master
