version: 0.0
os: linux
files:
  - source: demo.war
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "*.war"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh

